services:
  # web:
  #   build:
  #     context: .
  #     target: development
  #   container_name: hamker-dev
  #   ports:
  #     - "127.0.0.1:3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NODE_ENV=development
  #     - NEXT_TELEMETRY_DISABLED=1
  #   command: npm run dev

  web-prod:
    restart: always
    build:
      context: .
      target: production
    container_name: hamker-prod
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
